version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bwa-storegg-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/bwa_storegg
      - SECRET=SECRET
    depends_on:
      - mongo

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bwa-storegg-dev
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/bwa_storegg_dev
      - SECRET=SECRET
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: bwa-storegg-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
